from pydantic_settings import BaseSettings


class BaseConfig(BaseSettings):
    """Base Config for each configuration. All used env. variables 
    should be declared here. 

    See Also:
        DevelopConfig, ProductionConfig
    """
    APP_NAME: str = ''
    PLATFORM: str = ...
    
    APP_PORT: int = ...
    
    DEVELOP: bool = ...
    DEBUG: bool = ...
    
    TOPIC: str = ...
    KAFKA_BOOTSTRAP_SERVERS: str = ...
    CONSUME_TOPIC: str = ...

    DATABASE_URL: str = ...

    REDIS_HOST: str = ...
    REDIS_PORT: str = ...
    REDIS_URL: str = f"redis://{REDIS_HOST}:{REDIS_PORT}"


    class Config:
        env_file = ".env"
